---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAGTCkUkEkQ2X1rlhlda+Keg9sWm7GFFgWCqyGjnYxJEDC+po5KGMo1ocVOaIzWJQgvkFwFFKYldq9vMRoxstrFuD9FgadjCZR0/a9U2hg4b7BdoGCFwTp2fqSnzvBgDVHi7nGeeuIH6RF5kwObooZOWSzy+YHEl5WE9/m+OV2menlKG9PiIGnPwZ2OUPzgkR9vwNnm9zA/7xlVIbPbBfp5NkqZvNC2ZdlJE6NPZOo4CiQUrZX5I4c4tukYXKzVBRKG2TZtGU/vwoo4wds1tRENzlCnbV8yXbkPU3dvlF5DrgQMuLUP4c/JIiZLTsNdjoZBqU/+sFZJFVBwKWSQvy6zPAKupMh/ybmhuiuko/VhuCugqPeKfeFRCi0anwRTZFVmnAJyzgXaoQfxo7emWfgatya+Mikw4XY1NUauyapO8FJfdQokC28dXfr8lCpsOCwhMLceW4qeQ2OP/R++khlPA0Uq9buI7JVDZGDFii7r55NvODGXeU7xp3Y9r5Vh5c//LdHUG+/cLC1Q+YZPGeGeHLeDDXHTQJhoz0QKP6KpkI7Ae23Gp63yQtW9663Xu70clB8uBcF/69VVYyIX4lW0MhDMRhrQ1JtPQopez9NLymB+dRwZfdxZDWH1K+Ez9DtOQCfqApuntBXCWXQm21M65vL1GpsdH8wK6f01jVQ+R2PY6DvBm01PZIs3yxdbmmY5c1wLBifADHVlwfXth1LoH81RCq3ba/1Z6sL7ht2yiCk7ilylRSc9hd8oh9spynOTw2Y9f9KDSPzj3t+UkZDtn1u25WoIBfAwRbwKgCR2qKvZi6dYygeBJSMjR/zW2G1tJI15+eDNnmWK/wCEDE0YKAoeWKBKtcwHpCB0d5GdKjfUmiwMFB5JBa0b+GgBc0bOAaEgaJmsARxJH6NU6z7a+uUjs4ej8yaTRjGzGMJ7qCxDSGFevQnoug13KP/W236SEc9c5+U6BTeRqP2LMxyUCF9MmmNo/pw5q5+8Qxb/phbD1Lv+pTEXV/y3c6BrhC58BgYHj3KTypFE8aAenKKWaBY+koEwYpEvraXafs5SO28xyijyeOuTllrn9hYJFAzduHmPi6+YrUbu7Ayy13DyAIfiWEYrFGFuQ3uXB5nKiLttRZVSYiXQpgI0WQFdBmQ/UWdCX1fEdMA08+nyWmT1nSMFRfGzORJ+Ij9hY77jOyr6/9KP5TUs+q8UM3TcodTXz38ANBmLpiEfHkRD
  template:
    metadata:
      name: alertmanager-kube-prometheus-stack-alertmanager
      namespace: monitoring
