apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: clients-db
  namespace: clients
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "64MB"

  bootstrap:
    initdb:
      database: clients_db
      owner: clients_user
      secret:
        name: clients-db-secret

  storage:
    size: 1Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
