---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clients-db-secret
  namespace: clients
spec:
  encryptedData:
    password: AgA8/PXxcU/VOfmtNnV1OxJFmJYXy24lj3ffJZGljhzYzHfjhI5R5F8Ms3r5lKoZVGj0Jz5FULH8B5/vHn0pLO/2OlYhEDplGgcrnJO2uuSC9mWWBN/xKtxn8thBpW7Mz/vTfw1Yr4abbCen2ZVYODdUNQBInCYQXe7aBXbiKFIBCZF5Q0BThLoQWoFIgANGHj0sazByJIlPunRa72ILRcl7dt9FGbCcBTLq8UwTktsPJ77X5L9WUefHHrasxbmgBvXZ3FuziMjF5FTNEFII1AB6F44aRz7veUEFxj8oSFon4MBs0oq3jyDZhbEkZmp5ynbledOUuOhpLjnSnYRYRV1XnIAZCFAu+Bbhwpdr85nb7uFbB5K2IinhjK8zl/NA15AbN5WX5a+ECR062Y22CGQJ+61cVQAaoKUAC7k3lq8uGWm4uYxtVj0kLhkXQV3lXFp9UKHyLH4T0qNnE0VTSdwc87yd4CAAt27vCdtqtliDQ7g4FLwYRDgMJ2tZJ5bJrfAQkc53G3E/rbDqTWm4K5DuCTtK9qiUR2PY8V7iPIlwo0Z+ngAzt/ARGLQzcN1P68Rgb4uiCGp931n2GhIr3W1lRZcfDJjkqTg167C6lcxA6oZqEIdw1d/sZAqAu1e7wmXc+u//rWDWgA1k0DaZpX936Zsv5cKS5SrLl8m7XcPg/LE6SbNyLz2L715eNCoOjoeCQ0ghzwpwS2FNLw==
    username: AgAAh9wJlasbfbkEUA9WFMIpuuZqO4MUlyzKeY5rACNaSbKBCoOoDKuVz48rTDgsSn9a3CRwhBp1dBSk4g0AoQ+w4Svpte037Y0Sm3s6gl8UOcWhEVGMAiZHPO63bp3r5uJQEVZ29DR9jLzS8LfWVwtXb/bsUJn6U20EaePIUBU/7I77M4ct1y1NcDUGaOZCteAhRtIHr9qtqNDoD8+aBEQWnzWpeYlj4vCUaPA1hyPglghm/axelCapK1QxN+CoG0IYMdts28KFJwK8ymfpZ5I6M/gAshzaKXyuzgumNo/DI/eWVbuUEFEUdpo1N/hYMzJmdjdpt0igTT9H9e4QzKJ0Y8KpSs7MJDBn4jm4UTEIkUVPTBZ+U6URLuYdeoPGxS5I3twDx9kSviG+mt8rukezOQW8vk3aGH2eDWBSxgU55fCG6wMx/TkXp0RSswkNt15UXKdxk4sQWJTlcu0Eyrrr8hI2mJB21hsmwxYNFkBckTRIho9QgSZayzk55ISC+bSDez0vtsS8NNg9QhV0uY0Wlz2GooNHnXDwReqSN9tMcYk4qrmm4SdUjd2A0ytPPtyK2AbvlYLsjAfK6CWeG3j6ZO7cIh3USa5Fs+3MmHEbSBy4mxDjnVEyMq/Na7nTbhcvhXQx6YZWUXvZuBPjFY1XwPhjNjo/f5TYsUtYoiyv124yQamShFRls01u/mMYeXnGjv0TTXeHKhPOA+g=
  template:
    metadata:
      name: clients-db-secret
      namespace: clients
