---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clients-db-secret
  namespace: clients-staging
spec:
  encryptedData:
    password: AgArWFeyuvyqkcSWEwQZ03B4mqB39vXAmNel56sY0CcXYm5neiTP32/FxjSfUkHJj6ihMrEbPPhKGkqjWBrGFuAvRSRn6TEOznl5KZUrB480iQZcS9ksVIX7wSIMFrHL+YFJFFHC5ZCBHfRKXe3G/jpd0m2Sp8Dh1gcFqCBcfjW11nwwyL/V+TOv9TSpogXMfieDuUbkShjRUnvHDFqo1KY/Ht4uaExNeYvVT0dnxV8uP7ChOVqbD0qp+A6sB3hC/Jci6gRIcwNlOEPnX0PkMuLuIqZs4FSRPfoLNxi9fVqXUl49bDn2faSw6iuNx4XSLVPkUnuCS11APqk+LJsWQe2bLuNJ+4op/K3sEqBHgWtDm0wbyYpUM+Jwok4UC+fFORm1yPmB5rLQZmlBI4BuscYkpnB3msXzd1oorA8jH+HFAhouETsD0DD3LdCTY2W6RyAFsssP81wP171AFuIMa4HzIivePTyPgXHoGrw2jZZJZBt+GvD23b2ryaYMpm4bKGDq+TRu6r0gS20G+f4O5uaV/2vbYLOzKoFGUEOXhBGzVm758b+tWf1Rd1Y/fztta2fckGHPzgyyhONVA0py2OSznZw1voqXOWLxKSUf/YukRWfIPgklam4TUVJmTYEe/YrR8Za+UIY1MkVm28QwCjazjabL0rp5JtCtSC8izi/n6dGPvIOcDhxcgqnMJQNn9eLeNxj9ROUt+V1v2Q==
    username: AgBDAGz1e+XO+1py94AZHISObnwYMi6QrvI76vp+W6ii/kKSvNkuULSxyrGfyrcrwNhhNej19SET/0AviH/MSM2/s4sWS2NagQL4nWSSS0mWdKHxBvcv+8nU6cM2vGiUEgO7t44/4erVDl2ttyKkCvBhv8Fk3pAJuMfZyvK9P9NuA7J2RCG/yejvH6heFHSSDpMokkxk6twCuy5+BYxYY7U0msOAq5MMeozI7Xc42JFvLo/8LiSqoLA8bT1x0Ob4kcMl90zgAhjD9ZeLk0BYs+XMG8YkPOgoSSLIVRgLDW3e+z9V6hhipOgOwbt5QoUMntf3VQC0zv9rewCGb5qRJQgtGlD9WZsak1uO1O4ytSBzQEZkZlOpuHHI2h4X+6s9TTiWP520K5KqyEMfo2dSo0lVNPOnbFXzVSK+PKN+Y+uFrfa+GRAgzajSVQE5tXEBKOEQwBVKTRb2TmHRQLsqhANKM+TLccDjjCuyct+Y96PlVrcw5hWj4yycFdywwuYjiUMXR7ERA7GjkF98V8ebZ7Kjuzk/JYbnb6VPX/FcTlqmQIJuP6mcH0n21P0QkexIoqEYuROB+pxfIXG4oIMkihqIKo46CSWfMq4wdA2VG7yFHh4rNNjlHg1gJULBfNTuqIMfalJPd/jHMOhLEIWjqwEcU2E1ChGSreQmeQTlOB/amlHd/OqVyNre/F0j0BM85Ouz4BBcmNfjdUBuBwg=
  template:
    metadata:
      name: clients-db-secret
      namespace: clients-staging
