apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clients-api-staging
  namespace: clients-staging
spec:
  interval: 5m
  chart:
    spec:
      chart: clients-api
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: clients-api
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    springProfile: prod
    replicaCount: 1
    image:
      tag: "1.5.4" # {"$imagepolicy": "flux-system:clients-api-staging:tag"}
    database:
      host: clients-db-staging-rw
      port: 5432
      name: clients_db_staging
      credentialsSecret: clients-db-secret
    ingress:
      host: clients-api-staging.cluster.kcn333.com
    autoscaling:
      enabled: false
    pdb:
      enabled: false
    serviceMonitor:
      enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
      initialDelaySeconds: 120
      periodSeconds: 10
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
      initialDelaySeconds: 90
      periodSeconds: 10
      failureThreshold: 5
