apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-staging
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kCn3333/k3s-homelab
  ref:
    branch: staging
  secretRef:
    name: flux-system
