apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-system-staging
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-staging
  git:
    checkout:
      ref:
        branch: staging
    commit:
      author:
        email: fluxbot@kcn333.com
        name: fluxbot
      messageTemplate: 'chore(flux): update staging image tags'
    push:
      branch: staging
  update:
    path: ./apps/staging
    strategy: Setters
