---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgCcmP/tfjSlxSyvTWaZ8St+Rl92dQtGWKohScfIrN6m8UMPiYhKTWFdgiL/xY+yq/dIJYozqTHZzbW7mKK+9LDe7vByertuKnLpVUbHnYnffLRQ9zjRZDPWHZyW9tjR9tWzO9C4I3CNaAksspRpFJGf0w8Ir8yi/wLEAnG9h4zdobh3hCZoOnf0s+Fi/DSx1amZX/PpchHmPyNu6oVpaZppI4czSq1wJquuG/fiDoLrsRtXwfGwh8nQTG2RKvwaqwQ+dz19glhVDap51v3EpxzE9sHgvr/NzJVZ2YSxURnrV9+PJ0qnY5kC6XWaffVS3ne1yfZY/UB9CxYBM8zSsjHmvgjp92gvOu2vLRNef3kziZD+C5jPCWaxh1qbKwZ6fsOFq0N0Hz+9fy/ayb+mC1aeQdzPJBT6H5PkqnYx2bloUx3psZ96fF5R8rzdc0fS4DiKiWwADPv/aygW6Mjl8N54/PG1BKKfvs3pCgpI13y8JZZuDY1nQGooalN7nEiKowSQBx4Vo2oJ6Zorw/C0vPzSQF6/0X9PSxOQ3LuDmyKqXczo63P0OhJQHdmhsPqyOmPL+qFxQqKXcu9bUAG2h5pJynrsseQrwWPSCZ6y+euZQgvirWIhXfSDarxlstSjWe/q1176W16a2LcNxA4u+7lYqSrTbeBC/WsVGhlvX7DQrkmXMnOjygDL9goKIV9yK/w/KU8jW3BKstdJ8M09eKlL0YMKSknZq2aPVearBqnyF+LlGNiavhaVsfX2NxowlVbugOh9yQwYqIdfJwfOl9J2hoPUiVtDMf7ZxMm/6s0/P6MOTtApnWnCtPIIC9zxASKBpAXC/8j7u7ZwiPzSeLMDiwKjSFvaQfkAPVfXfAvZ8F9SNYIXKMMqVYL9FUawSX1i9MRReyP8ZNtc47MpNZ1xbOLxTlNhkZRW9MEM0sHBq0iS48x+Iu9Xd4701KawwfGGtKwv4AZfstg49wccYJ8rMIJHjL6eVexOJc8uBlVqSoLJCZEs8AONuXqZ6i0Gdr2z8Ox5e4tM15REyeg9AEaYAxVoHohUoSAz60v7idMzhonom6+aLe9r101YA5DXn3p65+zIvDahF7a89D2dy3DWlUS9FCUUVZXCXdSwoN3Q2auYmVjQyeozo4qOu1BeoMnqapRvi1PMrbdkB95HMI89SfvvHMcI/KYm5LPvWPnt8wjSfzhdGQ==
  template:
    metadata:
      name: alertmanager-kube-prometheus-stack-alertmanager
      namespace: monitoring
