---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAkCq0WhL51/ZW6EGzhHPu3Wyc0zWkqNSyUWmqMzleO0xcv4UZWZXe98Cil4gYVB9JpBGIBZ6jWjoGjqJZNhBhiZnFZXNEZBFbk78WlvAXoD9SobF6IZI49C9WUpHtfNaxeezWIM4cqY4vx0bsQkylZaMsQDevUMy9mrhsr+tFbxZA6SSFSSwuBk0/kZa7RtPif6Yjo1rRqzfvHeP7lTviZCTnUi2AEE2X83hhFwlGON6A5AWeVYydvJqSu3NcNBDEYZ0t2yPU3wyNpLO3exEtwOz9L61FJQom66fUzXaWYc3sK3HhwvRAKNfnzZymP8Em8d3IN4/Jwy5IZL8Mcfr375h2aM6UWmSNy78FjDdJlfLt/dT8dMaMfHM7jUacnR0id+sX0Zh/Glr8TalaivJSTjC+K06GZj6A0M4UYbDwNK42qkWYeRgG7wCsxto7sluGhR4kOd2vAvAdUbttD8ZyEht6QjyPcy8dva8HeABL7f3N6m8Dx7u0q70IZSSjeEwayjyIZW6N1giQ/T7ZDf2OVj/p0KmWuntcQyfWpLKqaKti/gJKDWDHtoL2e8wGDml1tZ2SbWJsWgMzhUj/Zw2rezd6s6KCMGxMa/W0QbIQlZOCdhNrejpqk8ekG5kpRtGpL54/o1w9bZC62spuhuApwgAPRfzJxmE9e3pR3ZGsJOVJxexomzayKJRqTtU17fUIwM7HXTxv/ySGNnM7YBhOpoE5PYbnM2bO1yKflgZJaumkRHs9bQkN6iIF58qX/8u2G501Wt9W47XAi7KRhdgUY5b9A39WNZxmayNlPSsY/02BRoN+02Y0j+ZILq4QA0bZbbAqdGHwkNqv27fmrL79TirUJRikM8vUlTIVuspdy3PqwpD/aCv+FluIJU5re9p2B/jE6TKpidAxEuxSY8oaw9kP63B6Onxqhot58vNXUhbSXq2FliNkARUI5VkV4+9tRPEjKtqE6n93+ezHIZ9eeJrqpao0OkSJ0SwkSAp78b1up40peuPbYl0PHClqIQYfxNtqA16d3b+UOpnqsgACmVQcGJ0UBntk/G00kmWY=
  template:
    metadata:
      name: alertmanager-kube-prometheus-stack-alertmanager
      namespace: monitoring
