{
 "title": "clinets-api-APP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"clients-api\"}[5m]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "DB Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"clients-api\"}\r\n* on(pod) group_left() kube_pod_info{namespace=\"clients\"}",
     "legendFormat": "{{pod}} active"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"clients-api\"}\r\n* on(pod) group_left() kube_pod_info{namespace=\"clients\"}",
     "legendFormat": "{{pod}} pending"
    }
   ]
  },
  {
   "title": "HTTP Requests Log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"clients\", pod=~\"clients-api.*\"} \r\n|= \"request\" \r\n!= \"/actuator\""
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by(le) (\r\n    rate(http_server_requests_seconds_bucket{\r\n      application=\"clients-api\",\r\n      uri=\"/api/clients\"\r\n    }[5m])\r\n  )\r\n) * 1000",
     "legendFormat": "p99 latency"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"clients-api\", status=~\"5..\"}[5m])) or vector(0)\r\n/\r\nsum(rate(http_server_requests_seconds_count{application=\"clients-api\"}[5m]))\r\n* 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"clients-api\", area=\"heap\"}\r\n* on(pod) group_left() kube_pod_info{namespace=\"clients\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}