---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAnQOFqTPshJCcvosxD73NfX7gvoOLGea634hwzXyRPLPxAdNdSDX2ZGVEA8ZjdfYzrljDA+5ylCLkLRoKm+7hqHayB/CmNMjQT6WxvQY/wk5bBpvWxrIpBSUkTVImdkZhZLq83RkmZkf0eghvwRHhsr1KimaBFEfuTd3hleYCGAHm+C+QBGmQnQ0iiYV0damGEUQKjuz1Sr0rYYibG0OAMAp5itkDOgnZmiScS3X/nfU9PJcHBg77Q6MZ5qX2GjpAsmpGDt+dlyzomLCMhd33AgUsypij2i5GfGNOeMEXKqKDPs2gDB9Utgnhni1XjpMPlY9oEVdecnfUv486raYeY0z7a+TI/ohlZUp3xt0sgc7v8R1D78aT8WLAyuLZDKZ6hZhfvEN3Sz0UNFURF7uMli8WVL949rbWrdRpGxUKz3Zni1blvghsk6U486jLhIu6k9L7C42048DyxJSdWdP/pBZ7G5lfoB8gkScoUrWdmXNGb2rIf/8sltaMDrG/zfNKmAEYNTrLAtoBkm3ZXi6wMBeG9eR7d1p9RKge+79K15nOmlLKgvO/s6/4HwzhO0pEJ9tvmTILAC5cKS7VqLSP3nLICyuF+etaShSBsOixNEWQdvSQ2QQD6xBh3OlqG3y6CCyRRtdVdDTxnbXdYYPgpNvClHzgEEv6e5mwXQuX9PAi1UMCCK8ZCLoKVT8khbNV1ipMCmBK3Jg8AgQ==
    admin-user: AgBLp4L7/5wsprv9a7hz9yZaVWgFnhoojqeWY7AImRUZ3Cewu4/3mp2SnoxraZHWAu33fXSLzQGYS8eZoKjaMw9GlK1C2nOO+/Wi+4J6TSbbVbfjmitioQpNUW1vXdAkqKOkGNWAxMLT0qQmTsaMZJY2pMnEchUUbLA231JVxg+p8sptH5qNOV9kAvHxbHzGl1u07wve/qFwxfvOHHyXx/QZGK5yXXH8pHIPCldeAtIn11dqqLtpnPiGkqsXAymUlzyt/fippNtsPyPMDzoCLo90kxJfM/eR1FfsHT9KQHQfih61FB2pcwY+4WmJI3fmFIdw8xJitKu3ykc21jvgU/ElOq/Nl5wXBH1ftbjgDcLxOR1eHN7xHhbx/OymkJ00xkYgcVP6sTLQrysGQF+6HEupHc2fs0OtYmflMm8QgNYpeuRhdo5h/IaPlxPmoa+pcGwMmlw5j8CUSFyOQQ5SLonvhH3KEgswt2N3enBMi3NGtGeDJD1rgbgc+RykPXW8vQ035y1vsuKbhTAjvDi69Xj/uSNO+IxHEh7S//lFyfOWEBa/sRYjL/vwFvFDJwJ/FFc4Q2cXVo/okYG15HboK9jNbXGWvIw6+FbiVJKZmYMqVioHrSEcdf2iVSjYdYj78GBfIJDfVYCqC8qoJJGvtJBDDSNhuoNaUTQbF9n+T086aCC/M33Eyzfy04uwOy0OCKRm0AzX0g==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
