---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-secret
  namespace: loki
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBUVUUjZWNYy3feLZJlqn5z6cPwvJWJkNzt+ZalEbZyzViHYzJySVdBiEr6oeXHS3lV+08c03WlPyQyLa0FdIZSsqq6Ge++155PneMCOxJtjWwQ14Ay/SxP1hBwpOmaXttUSL2IFXGyqlxqkv4h+HAJgZqxpPQF63c0zlfFIQq2gJmj7ZuNpiG5OOZYKUmiQExfC3a9j+/bdfGZgbZRWlYDfqZ+yKOz64R6PeQPBhTr9Jr9wv71LkZogxQqIDXxSmvVoHnoEOJhpSnEkW2xmt0gjGJLe3/zfkR38ZvKbOFPufyPLaEwT8/09eoR03Uf2wiuWy0vzLog+ZaHxWk3g2LS1l7TjnDrCwWVvt6QOpG+av9iYyJwsS061IM0i+WnLegmjGic8npQE88qALWfK1sXJJuhN1qcleWNmYHzLuiH67MAw5KzEk6ETyS0JZV6C4DffUucA2mp6Hi/LVS1uaUcpX1dHahfRpE/3ev1Y3HGzLTMONs7w6lmMnzK0bWD9oh/wRdTY870Qi625nJ1QdaveLeoskpvixgfMB/TnZuXARU583L8Hf20KYEenmCQy8H24HCoR8I1W3ZiEh+OOl3AgDKuXyMGHKGoSmVYdUov+V0f5h/0PpADR7xt/WPOqfYmfGkDYIFjpLydlsEEO46ZBEK3ag4Pdu8Vngo3hIjjo/c58NUOvD7ykjQ7qdkocCUoS4FN3iTp3i4EHlin3kcz3lfQuz+GWwGMYA==
    AWS_SECRET_ACCESS_KEY: AgB2R3OQ0NcQkz5hYAeulH7vVCwj2i9oTA1QiwFp0n8mDa1TOBHD4sMSQvxCLIEANYI0t3NJ3I5xWRyPym2HoXlhjxM1H89KAXV9cXk4ESszIQwkMLpjSkzCS+DF65ZktmPy1ZoKd4twBdnUnLlKuATEu2OWNwi/sCwe7RAP5stx7VmXAjDxdFjr977qCZ7k3MqOpFs6bv38o/bPsb1VJ938L4jR/WW3o/MBOpyJ46uUWDI1yy5gaw8RMB1ICSe5mbI06FEuqqg+dpj+Wb4CAdmTYas4U4vG04TbcEgPIgJhDMV3hhCEkQF3olBBty9ff7ETU+WRsX3MTzHJDivCV47HjrJwn7rj6wMPOFGaQLCJLbLpP4BnuuKNSnYr/h2Kyf+xxH+L+qL1KgtsTmJKQ1isf6kOkI4hH4pkonalTUYC22dyjYXInNtOiNX/PPVITsq/U+R23dZ0C/k0aQYzpZxg66tX+WXUwTFLxbKHPwppn3V++crCBsK7Y4/S/vgrEA6U9vUkGZLWZQ5ORYyGTMR6AEqH9Lgnbxd7115EKTVZ2ujM5udmaQ5Hu7nBR0bStGYv+MW3KKrwUJfpzI4aTWPSO70a+VdgP7QGZR8BOIrFA+zJAmeYo/iH5XCtAVm/FzAm0VeGOLl6G7N8Nu42PJ2bFIrGdJ+0r59TMx84e9EBMrNkOQJ3ehHdMbYeLI0BzS92Bif3T8cQLzmJq6GQOHZKLvPpNxAByK8bV4EAqwjN+oxAWcFFKLLB2tjri0AyV3Vr9xeweTqYcQQvGS9Dt5gW
  template:
    metadata:
      name: loki-s3-secret
      namespace: loki
